sudo: false
language: ruby
cache: bundler
rvm:
  - 2.7.2

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "dlrm741@naver.com"
  - git config --global user.name "LEESONGHO"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "xNC2n+pAbFcD9aNFSwWchOkKbdwCeO4YGHmKrBJrYIRzLJidw+A//ba1Ys4s1DQ/tH3ApxT/o/sNIH0LzJHzWCi08vg36tFwEgN+9H9NGHu0AarUbNL44dyIEjzpgkOyfObDs9RiOGbQG08ofV7WTrd9DucVQrIb5WsryKD85dL8LUej+V6Y38IXtiFn7hBnN2cFgFpyELiBR5yGK1g9kq/TRKa0gx8G
    e0woQu2zcBDTB8/gU9iVeFM14FCE26ZwqvtTAmpoUY3uVZl7Aaol+THdQ5/8POGuuVyGbIJ91pP1ZpVCX/zLqNmwiYu7BjBHdN+2mP6jXRySNuUEztz2W+3fDZ9o9AiKUvhvD50H/csr36A43hgmDn8JHi1ziH+bZasUMebw3+8N/jitkOcbs5UrIFpZtqfW5NJGfOWZngDlXjsoSHBEAzeEcR9eftiLMxJi/hGnxbo
    5VTkULfY7o5kILimaD3qWaizL6EI/cNlG038afoXQOtjs59QPleWGDHokk/rygnbap+MIZUnxOrtl7qmbSC/1yXSKMUoHWsTFAdeViWxhUebSaVL7Jri7L8aMKDGUbpQPPRIb916vV9q8RzGB7T94+q5i9V6KljNx/zN/QSKi7TllIKZ2pBiuTSRk8ILyOOtguezRQeCoRbp2UFC4MORwDzP+0A7xDIc="
branches:
  only:
    - master